T30974
endlessm/eos-event-recorder-daemon pull request #244
Opened 2020-10-16 13:14 UTC by mschiu77

Fix the compatibility problem caused by the f"" string usage and subprocess.run

2020-10-19 22:12 UTC, jprvita commented
- Please split the mask / unmask changes into its own separate commit -- having each commit implementing only one thing (as much as possible) makes the review process a lot easier. And on those changes, let's not change the `metrics_unit` API -- let's keep the callers passing "start" or "stop", and encapsulate the extra necessary steps in `metrics_unit`'s implementation.
- The changes from f-strings to .format look good, except that they introduce some long lines that are likely to break the coding style. Please run each commit through [black](https://github.com/psf/black) and clean any warnings.
- The changes from `.run` to `.call` look good to me, but I haven't tested them yet.
- Finally, please make sure to always add a link to the phabricator task on each commit message, and on the PR description, so our phabricator integrations work correctly.

2020-10-19 22:13 UTC, jprvita requested changes
- Please split the mask / unmask changes into its own separate commit -- having each commit implementing only one thing (as much as possible) makes the review process a lot easier. And on those changes, let's not change the `metrics_unit` API -- let's keep the callers passing "start" or "stop", and encapsulate the extra necessary steps in `metrics_unit`'s implementation.
- The changes from f-strings to .format look good, except that they introduce some long lines that are likely to break the coding style. Please run each commit through [black](https://github.com/psf/black) and clean any warnings.
- The changes from `.run` to `.call` look good to me, but I haven't tested them yet.
- Finally, please make sure to always add a link to the phabricator task on each commit message, and on the PR description, so our phabricator integrations work correctly.

2020-10-20 03:36 UTC, mschiu77 commented
I do the mask/unmask thing in another T30975. I didn't notice that it's also in this this PR. Thanks for pointing that out.

2020-10-20 04:03 UTC, jprvita requested changes
I think you missed what black suggested -- when I run it on your latest branch it still changed those strings you are concatenating with `+`. But I suggest getting rid of the `+` altogether and only calling `.format()` once per string, as in the inline suggestions here.

But please apply them directly to the commit introducing the change (the f-string one) instead of accepting them in github, which I think will create a fixup commit on the tip of the branch instead. This keep the history a bit cleaner.

2020-10-20 04:03 UTC, jprvita commented on tools/eos-metrics-collector.exe
> +            "metrics data size ({} bytes), aborting.".format(data_size)
```suggestion
            "Insufficient free space ({} bytes) for metrics data size "
            "({} bytes), aborting.".format(free_space, data_size)
```

2020-10-20 17:55 UTC, jprvita approved these changes

2020-10-21 00:04 UTC, merged